theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
title: Secured Arch Linux Installation
description: Arch Linux installation using BTRFS on Full Disk Encryption and Secure Boot 
markdown: kramdown
author: Chady Morra
